/** @format */

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '300', '500', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Wisecam',
	description: 'Generated by create next app',
	icons: '/favicon.png',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-BR'>
			<body className={poppins.className}>{children}</body>
		</html>
	);
}
